### ISSUE TITLE
Dynamic difficulty

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-block-producer#26]
We need to determine how difficulty is adjusted over time. A possible implementation would keep a rolling 1-day window of the number of blocks produced in one day and use that to adjust the difficulty.

**Deliverable:** Formula for adjust difficulty over time

**Comment by mvandeberg** [comment]
In the process of implementing the pow contract, I came up with the following algorithm:

```
block_window_time = ( block_window_time * 8639 ) / 8640; // Decay one interval
block_window_time += current_block_time - last_block_time; // Add current interval
average_block_interval_ms = block_window_time * 1000 / 8640; // Get block interval average in ms
block_time_diff = average_block_interval_ms - 10000; // Get difference between average and desired block interval

if ( current_block_time / 600 > last_block_time / 600 ) // Update block interval once per minute
{
   current_difficulty += ( current_difficulty * block_time_diff ) / 10000;
}
```

The last two calculations are the most important. If the block interval is too long, `block_diff_time` is positive. If it is too short, `block_time_diff` is negative. Once per minute, the difficulty is updated according to how far off the average block interval is. If blocks are being produced twice as fast, then the difficulty target will be halved. Likewise, if the block interval is half as much, the difficulty target with be doubled.
